import type { Cat3, LayoutConfig, PlacedTile, TileAnswer, TileRole, WordPair } from '../domain/types'
import { LEAN_NOTCHES, STRENGTH_VALUES } from '../domain/types'

/**
 * Answer[] -> PlacedTile[]. A pure function, and it must stay pure: no Math.random,
 * no Date.now, no Map/object iteration order dependence.
 *
 * The determinism is a hard requirement, not a preference. Saving a profile promises
 * that reopening it reproduces the same artwork, and the paper is on this side too:
 * "chaos describes behavior that appears random but actually is produced by
 * DETERMINISTIC, nonlinear dynamical systems" (p. 1132), and its characteristic (c) is
 * that "complex behavior can be generated by the system itself and not just by system
 * inputs". Injecting noise into the inputs would make the complexity come from the
 * noise, which is the case the paper explicitly distinguishes itself from. Sensitive
 * dependence belongs in the optimizer, which genuinely has it.
 */

export const DEFAULT_LAYOUT: LayoutConfig = Object.freeze({
  gridSize: 96,
  rimRadius: 0.92,
  minRadius: 0.10,
  radialExponent: 1.35,
  purityFloor: 0.55,
  // 0.055 * R_max keeps sigmaMin (2.59 elements at N=96) at or above the sensitivity
  // filter radius (2.2). If sigma < filterRadius the filter erases the seed structure
  // before the optimizer can act on it, and every profile produces the same art.
  sigmaBase: 0.055,
  invertAnchors: false,
})

/** Arc-length jitter budget, in units of R_max. */
const JITTER_HASH = 0.05
const JITTER_LEAN = 0.045
/** Hard cap so a blend can never leave the span of its two parent sectors. */
const DELTA_THETA_CAP_DEG = 20
/** Below this purity an item has no categorical direction at all. */
const PURITY_EPSILON = 0.05
const RELAX_ITERATIONS = 20
const RELAX_STRENGTH = 0.6
/** Separation floor in element widths. */
const RELAX_MIN_SEP_ELEMS = 2.5

/** Immutability band thresholds. See boundary.ts for the final anchor/load selection. */
export const M_ANCHOR = 0.75
export const M_LOAD = 0.45

const SQRT3_OVER_2 = Math.sqrt(3) / 2
const DEG = 180 / Math.PI

/**
 * FNV-1a over the pair id, mapped to [0,1). Used for jitter and for the theta fallback
 * on category-neutral items.
 *
 * Keyed on the ID and never on an array index: if it were index-based, inserting a pair
 * into the library would reshuffle every existing user's artwork.
 */
export function hashUnit(s: string): number {
  let h = 0x811c9dc5
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i)
    h = Math.imul(h, 0x01000193) >>> 0
  }
  return h / 0x100000000
}

/** L1-normalize a non-negative weight vector. Returns an equal split if it is degenerate. */
export function normalizeMix(c: Cat3): Cat3 {
  const r = Math.max(0, c[0])
  const g = Math.max(0, c[1])
  const b = Math.max(0, c[2])
  const s = r + g + b
  if (s < 1e-12) return [1 / 3, 1 / 3, 1 / 3]
  return [r / s, g / s, b / s]
}

/**
 * The hue actually used for placement and colour, after applying the pair's polar skew.
 *
 * This is the principled channel by which slider position changes GEOMETRY rather than
 * merely tint. A-FAM-03 ("Family is who I was born to" / "Family is who I chose") has
 * the largest skew in the library: pole A resolves to (0.75, 0, 0.25) and pole B to
 * (0.15, 0, 0.85), which the circular mean below turns into ~75 deg of travel -- derived
 * entirely from meaning, with no arbitrary constant. Without it, two people answering
 * the same pair oppositely would get identical geometry and differ only in colour, and
 * the FEA (which sees stiffness and geometry, not hue) would build the same truss.
 */
export function effectiveHue(pair: WordPair, lean: number): Cat3 {
  if (!pair.skew) return normalizeMix(pair.mix)
  return normalizeMix([
    pair.mix[0] + lean * pair.skew[0],
    pair.mix[1] + lean * pair.skew[1],
    pair.mix[2] + lean * pair.skew[2],
  ])
}

export interface CircularMean {
  /** Degrees in [0, 360). */
  readonly thetaDeg: number
  /** |z| in [0,1]. 1 = pure, 0.5 = equal two-way blend, 0 = balanced three-way. */
  readonly purity: number
  /** True when purity is below PURITY_EPSILON, i.e. no angle is more true than another. */
  readonly degenerate: boolean
}

/**
 * Weighted circular mean of the three sector centres (60 / 180 / 300 deg).
 *
 *   z = w_r * e^(i*60) + w_g * e^(i*180) + w_b * e^(i*300)
 *     = (0.5*w_r - w_g + 0.5*w_b,  (sqrt3/2) * (w_r - w_b))          <- no trig needed
 *
 * Because the centres are 120 deg apart, each sector BOUNDARY is the angular bisector of
 * its two adjacent centres. So an equal two-way blend lands exactly on the boundary
 * between its two parent categories, with no special-casing:
 *
 *   (0.5, 0.5, 0) -> 120 deg   Yellow, Demographic/Geographic -- "Regional Heritage"
 *   (0, 0.5, 0.5) -> 240 deg   Cyan,   Geographic/Associative -- "Localized Communities"
 *   (0.5, 0, 0.5) ->   0 deg   Magenta, Associative/Demographic -- "Affinity Groups"
 *
 * Hybrid identities are therefore spatially BETWEEN their parents by construction, and
 * the trusses that form across those boundaries are literally the hybrid structure.
 *
 * Purity has a closed form for L1-normalized w, since all cos(mu_k - mu_l) = -1/2:
 *   |z|^2 = sum(w^2) - sum_{k<l}(w_k w_l) = 1 - 3 * sum_{k<l}(w_k w_l)
 */
export function circularMean(hue: Cat3): CircularMean {
  const [r, g, b] = hue
  const re = 0.5 * r - g + 0.5 * b
  const im = SQRT3_OVER_2 * (r - b)
  const purity2 = Math.max(0, 1 - 3 * (r * g + g * b + b * r))
  const purity = Math.sqrt(purity2)
  if (purity < PURITY_EPSILON) {
    return { thetaDeg: 0, purity, degenerate: true }
  }
  let deg = Math.atan2(im, re) * DEG
  if (deg < 0) deg += 360
  // A hue that is analytically magenta -- (0.5, 0, 0.5), theta = 0 -- can compute a
  // tiny NEGATIVE imaginary part in floating point when the two components differ in
  // the last bit (D-AGE-02 at pole A does exactly this). That gives an angle just below
  // zero, and adding 360 rounds to exactly 360, breaking the [0,360) contract.
  if (deg >= 360) deg -= 360
  return { thetaDeg: deg, purity, degenerate: false }
}

/**
 * Radius from immutability, modulated by purity.
 *
 *   rho(m)  = f + (1 - f) * m^alpha           f = minRadius/rimRadius, alpha = 1.35
 *   r/R_max = rho(m) * (psiFloor + (1 - psiFloor) * psi)
 *
 * alpha > 1 (super-linear) because the library's immutability values cluster in
 * 0.35-0.60; a linear map would jam most nodes into one mid-radius annulus, which is bad
 * for the FEA (no long spans, no rim/core separation) and bad for the art. Super-linear
 * pulls the middle band inward and keeps the rim exclusive to genuinely fixed traits.
 *
 * The purity factor implements the degenerate-hue decision: an item with no categorical
 * direction cannot honestly be pinned to one rim sector, so low purity pulls it toward
 * the hub -- which is exactly where an integrating identity belongs, being the one place
 * equidistant from all three sectors. A perfectly white but immutable item still sits at
 * 0.55 * rho (a strong inner anchor, not a lost hub point); a white fluid item collapses
 * to the core. This makes white A PLACE, not just a colour, and buys the "concordant
 * core / hubbed wheel" morphology for free.
 *
 * The minRadius floor matters more than it looks: without it, low-immutability items
 * collapse onto the exact hub, producing coincident nodes, a stress singularity, and --
 * if several loads land on one node -- a spuriously huge point force.
 */
export function radiusFraction(immutability: number, purity: number, cfg: LayoutConfig): number {
  const f = cfg.minRadius / cfg.rimRadius
  const m = Math.min(1, Math.max(0, immutability))
  const rho = f + (1 - f) * Math.pow(m, cfg.radialExponent)
  const psi = Math.min(1, Math.max(0, purity))
  return rho * (cfg.purityFloor + (1 - cfg.purityFloor) * psi)
}

/**
 * Deposit footprint. Both factors are semantic rather than tuning:
 *  - (1 + 0.8 * beta): a BALANCED answer spreads (the wide, soft merged/bicultural
 *    morphology); a COMMITTED answer concentrates into a tight, saturated node.
 *  - (1 + 0.4 * (1 - m)): immutable traits are crisp and hard-edged; fluid traits are
 *    diffuse clouds. Mechanically apt too -- a pinned boundary condition should be
 *    well-localized, a hobby should not be.
 *
 * The 1.5h floor is a real bug guard, not a nicety: below it a deposit can fall between
 * grid nodes and sample to nearly zero, so an answered pair silently contributes
 * nothing. That class of bug is hard to notice because the art still looks plausible.
 */
export function sigmaFor(polarity: number, immutability: number, cfg: LayoutConfig): number {
  const beta = 1 - polarity
  const h = 2 / cfg.gridSize
  const raw = cfg.sigmaBase * (1 + 0.8 * beta) * (1 + 0.4 * (1 - immutability))
  return Math.max(1.5 * h, raw)
}

function bandRole(immutability: number, invert: boolean): TileRole {
  const m = invert ? 1 - immutability : immutability
  if (m >= M_ANCHOR) return 'anchor'
  if (m <= M_LOAD) return 'load'
  return 'mass'
}

function poleLabel(pair: WordPair, lean: number): string {
  if (Math.abs(lean) < 1e-9) return 'equally both'
  return lean < 0 ? pair.poleA : pair.poleB
}

export interface PlacementInput {
  readonly answers: readonly TileAnswer[]
  /** Every pair referenced by `answers`, library and custom alike. */
  readonly pairs: ReadonlyMap<string, WordPair>
  readonly layout: LayoutConfig
}

/**
 * Closed-form placement, then a deterministic relaxation pass.
 *
 * Answers with strength 0 (Dormant) and answers referencing an unknown pair are skipped:
 * Dormant is a real kept state that contributes nothing, which is distinct from an
 * unanswered pair (simply absent from `answers`) and from a balanced answer at full
 * strength (the most diffuse STRONG material in the model).
 */
export function placeAnswers(input: PlacementInput): PlacedTile[] {
  const { answers, pairs, layout } = input

  // Sort by id so the relaxation below is order-independent. JS Map and object
  // iteration order will bite you here if you rely on insertion order.
  const active = answers
    .filter((a) => (STRENGTH_VALUES[a.strength] ?? 0) > 0 && pairs.has(a.pairId))
    .slice()
    .sort((p, q) => (p.pairId < q.pairId ? -1 : p.pairId > q.pairId ? 1 : 0))

  const capRad = (DELTA_THETA_CAP_DEG * Math.PI) / 180
  const fMin = layout.minRadius / layout.rimRadius

  interface Draft {
    tile: Omit<PlacedTile, 'thetaDeg' | 'x' | 'y'>
    rFrac: number
    thetaRad: number
    /** The un-jittered circular mean, so the sector cap can be re-enforced after relaxation. */
    baseRad: number
    capped: boolean
  }

  const drafts: Draft[] = active.map((a) => {
    const pair = pairs.get(a.pairId)!
    const lean = LEAN_NOTCHES[a.leanIndex] ?? 0
    const salience = STRENGTH_VALUES[a.strength] ?? 0
    const immutability = a.immutabilityOverride ?? pair.immutability

    const hue = effectiveHue(pair, lean)
    const { thetaDeg: meanDeg, purity, degenerate } = circularMean(hue)
    const rFrac = radiusFraction(immutability, purity, layout)

    // A category-neutral item has no true angle, so fall back to a stable hash. This is
    // harmless because the purity factor has already pulled it near the hub, where
    // angular position barely affects geometry. The important part is that this case is
    // handled AT ALL: atan2(0, 0) returns 0 in JavaScript rather than NaN, so a
    // perfectly integrated identity would otherwise be silently placed at 0 deg -- the
    // Associative/Demographic seam -- and nothing would look broken.
    const baseRad = degenerate
      ? hashUnit(pair.id) * 2 * Math.PI
      : (meanDeg * Math.PI) / 180

    // Jitter in ARC LENGTH, not angle. Arc length is r*dTheta, so a fixed dTheta would
    // give generous spacing at the rim and a dense knot at the hub -- exactly backwards,
    // since the core is where the fluid Avocation and Employer items pile up.
    const arc = JITTER_HASH * (2 * hashUnit(pair.id) - 1) + JITTER_LEAN * lean
    const dTheta = Math.max(-capRad, Math.min(capRad, arc / Math.max(rFrac, fMin)))

    const polarity = Math.abs(lean)
    return {
      rFrac,
      thetaRad: baseRad + dTheta,
      baseRad,
      // A category-neutral item has no sector to stay inside, so it is exempt from the
      // cap and free to be pushed anywhere around the hub.
      capped: !degenerate,
      tile: {
        answerId: a.answerId,
        pairId: a.pairId,
        label: `${pair.poleA} ↔ ${pair.poleB}`,
        activePole: poleLabel(pair, lean),
        hue,
        purity,
        lean,
        polarity,
        salience,
        immutability,
        radius: rFrac * layout.rimRadius,
        sigma: sigmaFor(polarity, immutability, layout) * layout.rimRadius,
        amplitude: salience,
        role: bandRole(immutability, layout.invertAnchors),
      },
    }
  })

  relaxAngles(drafts, layout)

  /**
   * Re-enforce the sector cap AFTER relaxation.
   *
   * The cap applied to the jitter above does not survive the relaxation pass, which
   * moves theta freely to separate coincident items -- so without this, a crowded core
   * item can be pushed more than 20 deg from its circular mean and drift out of the
   * span its parent categories cover, destroying the "theta = category" reading the
   * entire layout depends on.
   *
   * The trade-off is deliberate: the sector guarantee is a semantic invariant, while
   * the separation target is only a mesh-quality heuristic. So separation yields.
   */
  for (const d of drafts) {
    if (!d.capped) continue
    let delta = d.thetaRad - d.baseRad
    while (delta > Math.PI) delta -= 2 * Math.PI
    while (delta < -Math.PI) delta += 2 * Math.PI
    if (delta > capRad) d.thetaRad = d.baseRad + capRad
    else if (delta < -capRad) d.thetaRad = d.baseRad - capRad
  }

  return drafts.map((d) => {
    let deg = (d.thetaRad * DEG) % 360
    if (deg < 0) deg += 360
    const R = d.rFrac * layout.rimRadius
    return {
      ...d.tile,
      thetaDeg: deg,
      x: R * Math.cos(d.thetaRad),
      y: R * Math.sin(d.thetaRad),
    }
  })
}

/**
 * Push coincident items apart along the arc, then project each back onto its own circle
 * so only theta moves. Radius is preserved EXACTLY, which keeps the immutability
 * semantics literally true -- a rim pin never drifts inward.
 *
 * Deterministic because the caller sorted by id: a fixed iteration count, a fixed
 * order, and no RNG.
 */
function relaxAngles(
  drafts: { rFrac: number; thetaRad: number }[],
  cfg: LayoutConfig,
): void {
  const h = 2 / cfg.gridSize
  const dMin = RELAX_MIN_SEP_ELEMS * h
  const n = drafts.length
  if (n < 2) return

  for (let iter = 0; iter < RELAX_ITERATIONS; iter++) {
    let moved = false
    for (let i = 0; i < n; i++) {
      for (let j = i + 1; j < n; j++) {
        const a = drafts[i]!
        const b = drafts[j]!
        const ax = a.rFrac * Math.cos(a.thetaRad)
        const ay = a.rFrac * Math.sin(a.thetaRad)
        const bx = b.rFrac * Math.cos(b.thetaRad)
        const by = b.rFrac * Math.sin(b.thetaRad)
        let dx = bx - ax
        let dy = by - ay
        let dist = Math.hypot(dx, dy)
        if (dist >= dMin) continue

        // Exactly coincident: separate along a fixed axis rather than dividing by zero.
        if (dist < 1e-12) {
          dx = 1
          dy = 0
          dist = 1e-12
        }
        const push = 0.5 * (dMin - dist) * RELAX_STRENGTH
        const ux = dx / dist
        const uy = dy / dist

        a.thetaRad = reproject(ax - ux * push, ay - uy * push, a.thetaRad)
        b.thetaRad = reproject(bx + ux * push, by + uy * push, b.thetaRad)
        moved = true
      }
    }
    if (!moved) break
  }
}

/** Take the angle of a displaced point, keeping the original if it degenerated. */
function reproject(x: number, y: number, fallback: number): number {
  if (Math.abs(x) < 1e-12 && Math.abs(y) < 1e-12) return fallback
  return Math.atan2(y, x)
}
